name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install
        run: yarn install
      - name: Run ESLint
        run: yarn lint
